// Íconos pintados para la interfaz (fase 8; el de construir, colonial desde la renovación): recursos, medidores y barra inferior.
// Se pintan una vez en un lienzo pequeño y se usan como imágenes (data URL).
import { FR, mulberry, lienzo, pintar, ovalo, urlDe } from './fresco.js';

function icono(f, tam = 64) { const c = lienzo(tam, tam), g = c.getContext('2d'); g.translate(tam / 2, tam / 2); g.scale(tam / 24, tam / 24); f(g, mulberry(tam)); return urlDe(c); }
export const ICONOS = {
  oro: icono((g, r) => { ovalo(g, 0, 0, 9, 9, FR.ocre, r, { bw: .8 }); ovalo(g, 0, 0, 6.5, 6.5, FR.ocreClaro, r, { bw: .5, n: 1 }); g.strokeStyle = FR.verde; g.lineWidth = 1.2; g.beginPath(); g.arc(0, 0, 4.4, Math.PI * .2, Math.PI * .8, true); g.stroke(); }),
  deuda: icono((g, r) => { pintar(g, [[-8, -7], [8, -7], [8, 7], [-8, 7]], FR.sienaClara, r, { bw: .8 }); pintar(g, [[-6, -5], [6, -5], [6, 5], [-6, 5]], FR.ocreClaro, r, { bw: .5, n: 1 }); g.strokeStyle = FR.siena; g.lineWidth = .8; [-2.5, 0, 2.5].forEach(y => { g.beginPath(); g.moveTo(-4, y); g.lineTo(4, y); g.stroke(); }); }),
  alimento: icono((g, r) => { g.strokeStyle = FR.verde; g.lineWidth = 1.2; g.beginPath(); g.moveTo(0, 10); g.lineTo(0, -6); g.stroke(); for (let k = 0; k < 4; k++) { ovalo(g, -2.2, -5 + k * 3.4, 1.8, 2.6, FR.ocre, r, { bw: .5, n: 0 }); ovalo(g, 2.2, -5 + k * 3.4, 1.8, 2.6, FR.ocre, r, { bw: .5, n: 0 }); } ovalo(g, 0, -8.5, 1.6, 2.4, FR.ocre, r, { bw: .5, n: 0 }); }),
  poblacion: icono((g, r) => { ovalo(g, -4, -4, 3, 3.2, FR.piel[1], r, { bw: .6, n: 0 }); pintar(g, [[-8, 9], [-7, 1], [-1, 1], [0, 9]], FR.rojo, r, { bw: .6, n: 1 }); ovalo(g, 4, -2, 3, 3.2, FR.piel[0], r, { bw: .6, n: 0 }); pintar(g, [[0, 10], [1, 3], [7, 3], [8, 10]], FR.azul, r, { bw: .6, n: 1 }); }),
  agua: icono((g, r) => { pintar(g, [[-3, -9], [3, -9], [2, -6], [6, -2], [5, 5], [0, 10], [-5, 5], [-6, -2], [-2, -6]], FR.azul, r, { bw: .7, n: 2 }); g.strokeStyle = FR.cal; g.lineWidth = .9; g.beginPath(); g.moveTo(-3, 1); g.quadraticCurveTo(0, -1, 3, 1); g.stroke(); }),
  energia: icono((g, r) => { pintar(g, [[1, -10], [-6, 1.5], [-1.5, 1.5], [-3, 10], [6, -2.5], [1.5, -2.5], [4.5, -10]], FR.ocre, r, { bw: .8, n: 1 }); pintar(g, [[1, -8], [-3.5, 0.5], [0.5, 0.5], [-1, 6], [3.5, -1], [-0.5, -1], [2, -8]], FR.ocreClaro, r, { borde: false, n: 0 }); }),
  bienestar: icono((g, r) => { ovalo(g, 0, 0, 5.5, 5.5, FR.ocre, r, { bw: .7 }); g.strokeStyle = FR.ocreRojo; g.lineWidth = 1.4; for (let k = 0; k < 8; k++) { const a = k / 8 * Math.PI * 2; g.beginPath(); g.moveTo(Math.cos(a) * 7.5, Math.sin(a) * 7.5); g.lineTo(Math.cos(a) * 10, Math.sin(a) * 10); g.stroke(); } }),
  igualdad: icono((g, r) => { g.strokeStyle = FR.siena; g.lineWidth = 1.3; g.beginPath(); g.moveTo(0, 9); g.lineTo(0, -8); g.moveTo(-8, -6); g.lineTo(8, -6); g.moveTo(-5, 9); g.lineTo(5, 9); g.stroke(); [-7, 7].forEach(x => { pintar(g, [[x - 4, 0], [x + 4, 0], [x + 2.5, 3], [x - 2.5, 3]], FR.ocre, r, { bw: .6, n: 0 }); g.beginPath(); g.moveTo(x, -6); g.lineTo(x - 3.5, 0); g.moveTo(x, -6); g.lineTo(x + 3.5, 0); g.lineWidth = .5; g.stroke(); g.lineWidth = 1.3; }); }),
  legitimidad: icono((g, r) => { g.lineCap = 'round'; for (const s of [-1, 1]) { g.strokeStyle = FR.verdeOsc; g.lineWidth = 1; g.beginPath(); g.arc(0, 0, 8, Math.PI / 2 + s * .25, Math.PI / 2 + s * 2.6, s < 0); g.stroke(); for (let k = 0; k < 5; k++) { const a = Math.PI / 2 + s * (.6 + k * .45); g.save(); g.translate(Math.cos(a) * 8, Math.sin(a) * 8); g.rotate(a + (s > 0 ? .9 : -.9)); ovalo(g, 0, 0, 1.3, 3, FR.verde, r, { bw: .4, n: 0, j: .02 }); g.restore(); } } }),
  ambiente: icono((g, r) => { pintar(g, [[0, -10], [6, -3], [5, 5], [0, 9], [-5, 5], [-6, -3]], FR.verde, r, { bw: .7, n: 2 }); g.strokeStyle = FR.verdeOsc; g.lineWidth = .8; g.beginPath(); g.moveTo(0, -8); g.lineTo(0, 10); [-4, 0, 4].forEach(y => { g.moveTo(0, y); g.lineTo(-3.5, y - 3); g.moveTo(0, y); g.lineTo(3.5, y - 3); }); g.stroke(); }),
  rumbo: icono((g, r) => { ovalo(g, 0, 0, 9, 9, FR.cal, r, { bw: .7, n: 1 }); pintar(g, [[0, -8], [2, 0], [0, 8], [-2, 0]], FR.rojo, r, { bw: .5, n: 0 }); pintar(g, [[-8, 0], [0, -2], [8, 0], [0, 2]], FR.siena, r, { bw: .5, n: 0 }); }),
  // Casa colonial de cal y teja con zócalo verde, puerta de madera y una espadaña: el pueblo que se construye.
  construir: icono((g, r) => { pintar(g, [[-9, 9], [-9, -1], [5, -1], [5, 9]], FR.cal, r, { bw: .6, n: 1 }); pintar(g, [[-9, 9], [-9, 6.4], [5, 6.4], [5, 9]], '#3E6B4A', r, { bw: .5, n: 0 }); pintar(g, [[-3.6, 9], [-3.6, 3], [-.4, 3], [-.4, 9]], FR.sienaClara, r, { bw: .5, n: 0 }); pintar(g, [[-10.5, -1], [-2, -7.5], [6.5, -1]], FR.teja, r, { bw: .6, n: 1 }); g.strokeStyle = FR.siena; g.lineWidth = .5; g.globalAlpha = .5; [-6, -3, 0, 3].forEach(x => { g.beginPath(); g.moveTo(x, -1); g.lineTo(x * .3 - 1.4, -6); g.stroke(); }); g.globalAlpha = 1; pintar(g, [[6.5, 9], [6.5, -4], [10, -4], [10, 9]], FR.cal, r, { bw: .5, n: 0 }); pintar(g, [[6, -4], [8.25, -8.5], [10.5, -4]], FR.cal, r, { bw: .5, n: 0 }); g.fillStyle = FR.ocre; g.beginPath(); g.arc(8.25, -4.6, 1, 0, 7); g.fill(); }),
  hacienda: null, sociedad: null,
  leyes: icono((g, r) => { pintar(g, [[-8, -6], [8, -6], [8, 6], [-8, 6]], FR.ocreClaro, r, { bw: .7 }); ovalo(g, -8, 0, 2.2, 6, FR.sienaClara, r, { bw: .5, n: 0 }); ovalo(g, 8, 0, 2.2, 6, FR.sienaClara, r, { bw: .5, n: 0 }); g.strokeStyle = FR.siena; g.lineWidth = .7; [-3, 0, 3].forEach(y => { g.beginPath(); g.moveTo(-4, y); g.lineTo(4, y); g.stroke(); }); }),
  cronica: icono((g, r) => { pintar(g, [[-9, -7], [0, -5], [9, -7], [9, 8], [0, 9], [-9, 8]], FR.cal, r, { bw: .7, n: 1 }); g.strokeStyle = FR.siena; g.lineWidth = .8; g.beginPath(); g.moveTo(0, -5); g.lineTo(0, 9); g.stroke(); g.lineWidth = .5; [-2, 1, 4].forEach(y => { g.beginPath(); g.moveTo(-7, y); g.lineTo(-2, y + .5); g.moveTo(2, y + .5); g.lineTo(7, y); g.stroke(); }); })
};
ICONOS.hacienda = ICONOS.oro; ICONOS.sociedad = ICONOS.poblacion;

// Etiqueta <img> lista para insertar en el HTML de la interfaz.
export const ico = (k, clase = 'ic') => `<img class="${clase}" src="${ICONOS[k]}" alt="" aria-hidden="true">`;
